package message.client;

public enum MessageType {
    REGISTER,
    PICK_QUESTION,
    LOGIN,
    CHANGE_USERNAME,
    CHANGE_NICKNAME,
    FORGET_PASSWORD,
    ANSWER_Q,
    SET_NEW_PASSWORD,
    CHANGE_EMAIL,
    CHANGE_PASSWORD,
    SIGN_OUT,
    GIVE_FRIEND,
    ACCEPT_REQUEST,
    SEARCH,
    CHECK_SERVER, GEVE_ONLINE_FRIEND, PUP_UP, REJECT_REQUEST, CHANGE_GAME_MODE, ENTER_GAME, ENTER_GAMELOBBY, BACK_OFFLINE, RANDOM_GAME_REQUEST, FREAND_GAME_RQUEST, REJECT_FRIEND_REQUEST, ACCEPT_FRIEND_REQUEST, SEND_FRIEND_REQUEST, CHANGE_FACTION, GET_FACTION, SELECT_LEADER, GET_CARD_COLLECTION_DECK,


}
