package message.client;

public enum MessageType {
    REGISTER,
    PICK_QUESTION,
    LOGIN,
    CHANGE_USERNAME,
    CHANGE_NICKNAME,
    FORGET_PASSWORD,
    ANSWER_Q,
    SET_NEW_PASSWORD,
    CHANGE_EMAIL,
    CHANGE_PASSWORD,
    SIGN_OUT,
    GIVE_FRIEND,
    ACCEPT_REQUEST,
    SEARCH,


}
