package message.server;

public enum ServerType {
    POP_UP_MATCH_REQ_GAME_LOBBY, NO_POP_UP_MATCH_REQ_GAME_LOBBY, START_RAND_GAME, ACCEPTED_FRIEND_MATCH, SHARMANDE_KIR_SHODI, BOTH_HAVE_READY_DECK, NEW_ROUND, END_GAME, YOUR_TURN, START_FRIEND_GAME
}
